name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "dist/**"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate Snake SVGs
        run: |
          INPUT_GITHUB_USER_NAME="${{ github.repository_owner }}" \
          INPUT_OUTPUTS="dist/github-contribution-grid-snake-dark.svg?color_snake=%23a3e635&color_dots=%2301553d,%23057a55,%2310b981,%2322c55e,%23a3e635&color_dot_border=%2300080f
          dist/github-contribution-grid-snake.svg?color_snake=%23a3e635&color_dots=%2301553d,%23057a55,%2310b981,%2322c55e,%23a3e635&color_dot_border=%2300080f" \
          node scripts/generate_snake.js

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg dist/github-contribution-grid-snake-dark.svg
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: regenerate contribution snake game [skip ci]" && git push)
